name: Secrets audit

on: [pull_request, push]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: gitleaks-action
        uses: eshork/gitleaks-action@v1.0.0
